title: Portfolio Maker
description: Thinker // Designer // Learner

#---------------------------
#Navigation Menu 
nav:
- {name: About Me, link: '#'}
- {name: Works, link: '#'}
- {name: Clients, link: '#'}
- {name: Contact Us, link: '#'}

#--------------------------------------

#---------------------------
#Work Section 
project:
- {name: Kstart Seed, link: 'http://facebook.com', folder: 'pro-1'}
- {name: Kstart Seed, link: 'http://facebook.com', folder: 'pro-2'}
- {name: Kstart Seed Kstart Seed, link: 'http://facebook.com', folder: 'pro-3'}
- {name: Kstart Seed, link: 'http://facebook.com', folder: 'pro-4'}
- {name: Kstart Seed, link: 'http://facebook.com', folder: 'pro-5'}
- {name: Kstart Seed, link: 'http://facebook.com', folder: 'pro-6'}
- {name: Kstart Seed, link: 'http://facebook.com', folder: 'pro-7'}
- {name: Kstart Seed, link: 'http://facebook.com', folder: 'pro-8'}

#--------------------------------------

#--------------------------------------
#Skill Section 
skill:
- {name: Communication, value: '8'}
- {name: Organisation, value: '7'}
- {name: Learning, value: '6'}
- {name: Visual Design, value: '7'}
- {name: Front-End Design, value: '8'}
- {name: Wordpress, value: '8'}

#--------------------------------------
#--------------------------------------
#Contact Us 
contact-email: iankit17@gmail.com

#--------------------------------------